### ISSUE TITLE
Doesn't work with ES6

### ISSUE THREAD

**Issue by gmaclennan** [alanshaw/stripify#8]
The latest version of falafel on npm only uses acorn v1.2.2 which does not understand ES6. It trips up on `const` statements for me. There is an updated acorn in falafel master but it has not yet been published to npm: https://github.com/substack/node-falafel/pull/52

**Comment by alanshaw** [comment]
Resolved by https://github.com/alanshaw/stripify/commit/4ee458286383688da45e5b6de5469f246e6cddb4
